# Generated by Django 3.2.9 on 2022-03-05 20:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cubansites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
                ('title', models.TextField(verbose_name='Title')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('pub_date', models.DateTimeField(verbose_name='Published Date')),
                ('authors', models.ManyToManyField(to='cubansites.Author', verbose_name='Authors')),
                ('tags', models.ManyToManyField(to='cubansites.Tag', verbose_name='Tags')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubansites.website')),
            ],
        ),
    ]
